heading:
  default: "This is a header"
  max: 25

blurb:
  default: "Ius vitae ornatus at, ei mea sumo quot dicant. Ei tale democritum eos, in mea timeam accumsan forensibus. Ei his aperiam suavitate. Et debitis convenire sea, viris dictas latine."
  max: 180

sections:
  type: objects
  default: []
  schema:
    name: link section
    identifier: text
    properties:
      text:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 1000
      title:
        type: string
        validations:
          min_length: 1
          max_length: 1000
      links:
        type: objects
        schema:
          name: link
          identifier: text
          properties:
            text:
              type: string
              required: true
              validations:
                min_length: 1
                max_length: 1000
            url:
              type: string
              required: true
              validations:
                min_length: 1
                max_length: 2048
            target:
              type: enum
              default: _blank
              choices:
                - _blank
                - _self
                - _parent
                - _top
            title:
              type: string
              validations:
                min_length: 1
                max_length: 1000
            referrer_policy:
              type: enum
              default: no-referrer-when-downgrade
              choices:
                - no-referrer
                - no-referrer-when-downgrade
                - origin
                - origin-when-cross-origin
                - unsafe-url

small_links:
  type: objects
  default:
    - text: Privacy
      url: "#"
      target: _blank
    - text: Terms of service
      url: "#"
      target: _blank
    - text: About
      url: "#"
      target: _blank
  schema:
    name: small link
    identifier: text
    properties:
      text:
        type: string
        required: true
        validations:
          min: 1
          max: 1000
      url:
        type: string
        required: true
        validations:
          min: 1
          max: 2048
          url: true
      target:
        type: enum
        default: _blank
        choices:
          - _blank
          - _self
          - _parent
          - _top

social_links:
  type: list
  list_type: simple
  default: "Facebook, Join us on Facebook, #, blank,fab-facebook|Twitter, show some love on Twitter, #, blank,fab-twitter| Youtube, Check out our latest videos on Youtube, #, blank,fab-youtube"

show_footer_on_login_required_page:
  default: true

svg_icons:
  default: "fab-facebook|fab-twitter|fab-youtube"
  type: "list"
  list_type: "compact"
